// =============================================================================
// Health export writer: PDF report for a doctor (H7, #191)
// =============================================================================
//
// pdfkit (streams its output; no headless browser). A short, readable report
// of the selected datasets over the export range, built from ACTIVE readings
// only (the report is the current record; history belongs in the data
// formats):
//
//   header      name, age and sex at birth (age and sex only when the profile
//               dataset is selected), the period, the generation date and,
//               with labs, the lab units ("Lab units: SI")
//   labs        the latest result of each analyte, grouped by panel, with
//               the lab's reference range and flag, in the export's
//               `labUnits` (#234: values and limits converted for display)
//   trends      the last readings of key metrics, a sparkline per metric
//   summary     body and vitals: latest, 30-day average, min, max, count
//   wellness    "Wellness / mood": 7- and 30-day averages of the check-in
//               scores, the windows ending on the range's last day
//   documents   an index of kept documents (metadata only)
//   progress photos  an index of progress photos (day, pose, note; never the
//               image: the report is shared with a doctor, the photos are not)
//
// Every page carries the footer `PDF_FOOTER_TEXT` and a page number. The
// standard Helvetica font covers Latin-1; any other character in user text
// (a name, a file name) is printed as `?` rather than as a wrong glyph.
// =============================================================================

import type { Readable } from 'node:stream';

import { APP_NAME } from '@app/shared';
import PDFDocument from 'pdfkit';

import {
  fromCanonical,
  getMetric,
  LAB_PANELS,
  labDisplayUnit,
  type LabPanel,
  type LabUnits,
  unitDecimals,
} from '../../measurements/metric-registry';
import type { ExportReading, HealthExportData } from '../health-export-data';
import { HEALTH_EXPORT_DATASET_TITLES } from '../health-export.constants';

/** The footer on every page. */
export const PDF_FOOTER_TEXT = `Generated by ${APP_NAME} from user-entered and AI-extracted data. Not a medical record.`;

/** Section headings, exported for the tests. */
export const PDF_SECTIONS = {
  labs: 'Latest biomarkers',
  trends: 'Trends',
  summary: 'Vitals and body summary',
  wellness: HEALTH_EXPORT_DATASET_TITLES.wellness,
  documents: 'Documents',
  progressPhotos: HEALTH_EXPORT_DATASET_TITLES.progress_photos,
} as const;

const PANEL_LABELS: Record<LabPanel, string> = {
  lipids: 'Lipids',
  glycemic: 'Glycemic',
  cbc: 'Complete blood count',
  cmp: 'Metabolic panel',
  thyroid: 'Thyroid',
  iron: 'Iron',
  other: 'Other',
};

const BODY_KEYS = ['weight', 'body_fat_pct', 'waist_circumference'];
const VITAL_KEYS = ['bp_systolic', 'bp_diastolic', 'resting_hr'];
const WELLNESS_KEYS = ['energy', 'sleep_quality', 'muscle_soreness', 'stress'];
/** Lab analytes worth a trend table when they have repeated results. */
const LAB_TREND_KEYS = ['ldl_cholesterol', 'hdl_cholesterol', 'triglycerides', 'hba1c', 'fasting_glucose'];
const TREND_POINTS = 8;

const MARGIN = 50;
const FOOTER_RESERVE = 40;
const ROW_HEIGHT = 15;

/** `text` with characters outside the standard font's encoding replaced by `?`. */
export function pdfSafe(text: string): string {
  return text.replace(/[^\x20-\x7E\xA0-\xFF–—‘’“”•…]/g, '?');
}

/** The header line naming the lab units, exported for the tests. */
export const PDF_LAB_UNITS_LINE: Record<LabUnits, string> = {
  conventional: 'Lab units: US conventional',
  si: 'Lab units: SI',
};

/**
 * How one report shows values: canonical for every metric but lab analytes,
 * which follow the export's `labUnits` (#234). Display only.
 */
class Units {
  constructor(private readonly labUnits: LabUnits) {}

  /** The unit `metricKey` is shown in. */
  unit(metricKey: string): string {
    const metric = getMetric(metricKey);
    if (!metric) return '';
    if (metric.scale) return `${metric.scale.min}-${metric.scale.max}`;
    return metric.category === 'lab' ? labDisplayUnit(metric, this.labUnits) : metric.canonicalUnit;
  }

  /** A canonical value in the shown unit, unrounded (for sparklines). */
  value(metricKey: string, canonical: number): number {
    const metric = getMetric(metricKey);
    if (metric?.category !== 'lab') return canonical;
    return fromCanonical(metricKey, canonical, this.unit(metricKey));
  }

  /** A canonical value in the shown unit, at that unit's display precision. */
  format(metricKey: string, canonical: number): string {
    const metric = getMetric(metricKey);
    if (!metric) return canonical.toFixed(2);
    const decimals = metric.category === 'lab' ? unitDecimals(metricKey, this.unit(metricKey)) : metric.decimals;
    return this.value(metricKey, canonical).toFixed(decimals);
  }
}

function labelOf(metricKey: string): string {
  return getMetric(metricKey)?.label ?? metricKey;
}

function capitalise(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1).replace(/_/g, ' ');
}

function average(values: number[]): number | null {
  return values.length === 0 ? null : values.reduce((sum, value) => sum + value, 0) / values.length;
}

/** `YYYY-MM-DD` shifted by `days`. */
function shiftDay(day: string, days: number): string {
  return new Date(Date.parse(`${day}T00:00:00.000Z`) + days * 86_400_000).toISOString().slice(0, 10);
}

interface Column {
  header: string;
  width: number;
  align?: 'left' | 'right';
}

class Report {
  constructor(private readonly doc: PDFKit.PDFDocument) {}

  private get bottom(): number {
    return this.doc.page.height - this.doc.page.margins.bottom;
  }

  private get contentWidth(): number {
    return this.doc.page.width - MARGIN * 2;
  }

  ensureSpace(height: number): void {
    if (this.doc.y + height > this.bottom) {
      this.doc.addPage();
    }
  }

  heading(text: string): void {
    this.ensureSpace(50);
    this.doc.moveDown(0.8);
    this.doc.font('Helvetica-Bold').fontSize(14).fillColor('#000000').text(pdfSafe(text), MARGIN, this.doc.y);
    this.doc.moveDown(0.3);
  }

  subheading(text: string): void {
    this.ensureSpace(40);
    this.doc.moveDown(0.4);
    this.doc.font('Helvetica-Bold').fontSize(11).text(pdfSafe(text), MARGIN, this.doc.y);
    this.doc.moveDown(0.2);
  }

  line(text: string, options: { bold?: boolean; size?: number; color?: string } = {}): void {
    this.ensureSpace(ROW_HEIGHT);
    this.doc
      .font(options.bold ? 'Helvetica-Bold' : 'Helvetica')
      .fontSize(options.size ?? 10)
      .fillColor(options.color ?? '#000000')
      .text(pdfSafe(text), MARGIN, this.doc.y, { width: this.contentWidth });
    this.doc.fillColor('#000000');
  }

  empty(text = 'No readings in this period.'): void {
    this.line(text, { color: '#555555' });
  }

  /** One-line cells, truncated to fit; repeats the header after a page break. */
  table(columns: Column[], rows: string[][]): void {
    const drawRow = (cells: string[], bold: boolean): void => {
      this.doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9);
      let x = MARGIN;
      const y = this.doc.y;
      for (const [index, column] of columns.entries()) {
        const text = this.fit(pdfSafe(cells[index] ?? ''), column.width - 6);
        this.doc.text(text, x, y, { width: column.width - 6, align: column.align ?? 'left', lineBreak: false });
        x += column.width;
      }
      this.doc.y = y + ROW_HEIGHT;
      this.doc.x = MARGIN;
    };

    this.ensureSpace(ROW_HEIGHT * 2);
    drawRow(columns.map((column) => column.header), true);
    for (const row of rows) {
      if (this.doc.y + ROW_HEIGHT > this.bottom) {
        this.doc.addPage();
        drawRow(columns.map((column) => column.header), true);
      }
      drawRow(row, false);
    }
    this.doc.moveDown(0.3);
  }

  /** A small polyline of `values`, oldest first, at the current position. */
  sparkline(values: number[]): void {
    if (values.length < 2) return;
    const width = 160;
    const height = 28;
    this.ensureSpace(height + 6);
    const x0 = MARGIN;
    const y0 = this.doc.y;
    const min = Math.min(...values);
    const max = Math.max(...values);
    const span = max - min || 1;

    this.doc.save().lineWidth(1).strokeColor('#0f766e');
    values.forEach((value, index) => {
      const x = x0 + (index / (values.length - 1)) * width;
      const y = y0 + height - ((value - min) / span) * height;
      if (index === 0) this.doc.moveTo(x, y);
      else this.doc.lineTo(x, y);
    });
    this.doc.stroke().restore();
    this.doc.y = y0 + height + 6;
    this.doc.x = MARGIN;
  }

  private fit(text: string, width: number): string {
    if (this.doc.widthOfString(text) <= width) return text;
    let cut = text;
    while (cut.length > 1 && this.doc.widthOfString(`${cut}...`) > width) cut = cut.slice(0, -1);
    return `${cut}...`;
  }
}

function byMetric(readings: ExportReading[]): Map<string, ExportReading[]> {
  const map = new Map<string, ExportReading[]>();
  for (const reading of readings) {
    const list = map.get(reading.metricKey);
    if (list) list.push(reading);
    else map.set(reading.metricKey, [reading]);
  }
  for (const list of map.values()) list.sort((a, b) => a.measuredAt.getTime() - b.measuredAt.getTime());
  return map;
}

function writeHeader(report: Report, data: HealthExportData): void {
  report.line(`${APP_NAME} health report`, { bold: true, size: 18 });
  report.line(' ');
  report.line(`Name: ${data.userName ?? data.profile?.name ?? '-'}`);
  if (data.profile) {
    report.line(`Age: ${data.profile.ageYears ?? '-'}`);
    report.line(`Sex at birth: ${data.profile.sexAtBirth ? capitalise(data.profile.sexAtBirth) : '-'}`);
  }
  report.line(`Period: ${data.range.from} to ${data.range.to}`);
  report.line(`Generated: ${data.exportedAt.toISOString().slice(0, 10)}`);
  if (data.datasets.includes('labs')) report.line(PDF_LAB_UNITS_LINE[data.labUnits]);
}

function writeLabs(report: Report, readings: Map<string, ExportReading[]>, units: Units): void {
  report.heading(PDF_SECTIONS.labs);
  let any = false;

  for (const panel of LAB_PANELS) {
    const rows: string[][] = [];
    for (const [metricKey, list] of readings) {
      const metric = getMetric(metricKey);
      if (metric?.category !== 'lab' || metric.panel !== panel) continue;
      const latest = list[list.length - 1];
      const range =
        latest.referenceText ??
        (latest.referenceLow !== null || latest.referenceHigh !== null
          ? `${latest.referenceLow !== null ? units.format(metricKey, latest.referenceLow) : ''} - ${
              latest.referenceHigh !== null ? units.format(metricKey, latest.referenceHigh) : ''
            }`.trim()
          : '-');
      rows.push([
        metric.label,
        units.format(metricKey, latest.value),
        units.unit(metricKey),
        range,
        latest.flag ? capitalise(latest.flag) : '-',
        latest.day,
      ]);
    }
    if (rows.length === 0) continue;
    any = true;
    report.subheading(PANEL_LABELS[panel]);
    report.table(
      [
        { header: 'Analyte', width: 140 },
        { header: 'Value', width: 60, align: 'right' },
        { header: 'Unit', width: 60 },
        { header: 'Reference range', width: 95 },
        { header: 'Flag', width: 55 },
        { header: 'Date', width: 85 },
      ],
      rows,
    );
  }

  if (!any) report.empty('No lab results in this period.');
}

function writeTrends(report: Report, readings: Map<string, ExportReading[]>, keys: string[], units: Units): void {
  report.heading(PDF_SECTIONS.trends);
  let any = false;

  for (const metricKey of keys) {
    const list = readings.get(metricKey);
    if (!list || list.length < 2) continue;
    any = true;
    const recent = list.slice(-TREND_POINTS);
    report.subheading(`${labelOf(metricKey)} (${units.unit(metricKey)})`);
    report.sparkline(recent.map((reading) => units.value(metricKey, reading.value)));
    report.table(
      [
        { header: 'Date', width: 100 },
        { header: 'Value', width: 80, align: 'right' },
      ],
      recent.map((reading) => [reading.day, units.format(metricKey, reading.value)]),
    );
  }

  if (!any) report.empty('Not enough repeated readings in this period to show a trend.');
}

function writeSummary(
  report: Report,
  readings: Map<string, ExportReading[]>,
  keys: string[],
  to: string,
  units: Units,
): void {
  report.heading(PDF_SECTIONS.summary);
  const since = shiftDay(to, -29);
  const rows: string[][] = [];

  for (const metricKey of keys) {
    const list = readings.get(metricKey);
    if (!list || list.length === 0) continue;
    const latest = list[list.length - 1];
    const values = list.map((reading) => reading.value);
    const last30 = average(list.filter((reading) => reading.day >= since && reading.day <= to).map((r) => r.value));
    rows.push([
      `${labelOf(metricKey)} (${units.unit(metricKey)})`,
      units.format(metricKey, latest.value),
      latest.day,
      last30 === null ? '-' : units.format(metricKey, last30),
      units.format(metricKey, Math.min(...values)),
      units.format(metricKey, Math.max(...values)),
      String(list.length),
    ]);
  }

  if (rows.length === 0) {
    report.empty();
    return;
  }

  report.table(
    [
      { header: 'Metric', width: 140 },
      { header: 'Latest', width: 55, align: 'right' },
      { header: 'Date', width: 75 },
      { header: '30-day avg', width: 65, align: 'right' },
      { header: 'Min', width: 50, align: 'right' },
      { header: 'Max', width: 50, align: 'right' },
      { header: 'Readings', width: 60, align: 'right' },
    ],
    rows,
  );
}

function writeWellness(report: Report, readings: Map<string, ExportReading[]>, to: string): void {
  report.heading(PDF_SECTIONS.wellness);
  report.line('Daily check-in scores from 1 to 5. Windows end on the last day of the period.', {
    size: 9,
    color: '#555555',
  });
  const since7 = shiftDay(to, -6);
  const since30 = shiftDay(to, -29);
  const rows: string[][] = [];

  for (const metricKey of WELLNESS_KEYS) {
    const list = readings.get(metricKey) ?? [];
    const in7 = list.filter((reading) => reading.day >= since7 && reading.day <= to).map((r) => r.value);
    const in30 = list.filter((reading) => reading.day >= since30 && reading.day <= to).map((r) => r.value);
    const avg7 = average(in7);
    const avg30 = average(in30);
    const scale = getMetric(metricKey)?.scale;
    rows.push([
      labelOf(metricKey),
      scale ? `${scale.min} ${scale.lowLabel}, ${scale.max} ${scale.highLabel}` : '',
      avg7 === null ? '-' : avg7.toFixed(1),
      avg30 === null ? '-' : avg30.toFixed(1),
      String(in30.length),
    ]);
  }

  if (rows.every((row) => row[4] === '0')) {
    report.empty('No check-ins in the last 30 days of this period.');
    return;
  }

  report.table(
    [
      { header: 'Score', width: 100 },
      { header: 'Scale', width: 160 },
      { header: '7-day avg', width: 70, align: 'right' },
      { header: '30-day avg', width: 70, align: 'right' },
      { header: 'Days (30)', width: 65, align: 'right' },
    ],
    rows,
  );
}

function writeDocuments(report: Report, data: HealthExportData): void {
  report.heading(PDF_SECTIONS.documents);
  const table = data.tables.find((candidate) => candidate.dataset === 'documents');
  if (!table || table.rows.length === 0) {
    report.empty('No kept documents in this period.');
    return;
  }
  report.table(
    [
      { header: 'File name', width: 230 },
      { header: 'Kind', width: 90 },
      { header: 'Date', width: 85 },
      { header: 'Type', width: 90 },
    ],
    table.rows.map((row) => [
      String(row.original_name ?? ''),
      capitalise(String(row.kind ?? '')),
      String(row.document_date ?? String(row.uploaded_at ?? '').slice(0, 10)),
      String(row.mime_type ?? ''),
    ]),
  );
}

function writeProgressPhotos(report: Report, data: HealthExportData): void {
  report.heading(PDF_SECTIONS.progressPhotos);
  const table = data.tables.find((candidate) => candidate.dataset === 'progress_photos');
  if (!table || table.rows.length === 0) {
    report.empty('No progress photos in this period.');
    return;
  }
  report.table(
    [
      { header: 'Date', width: 85 },
      { header: 'Pose', width: 80 },
      { header: 'Note', width: 330 },
    ],
    table.rows.map((row) => [String(row.date ?? ''), capitalise(String(row.pose ?? '')), String(row.note ?? '')]),
  );
}

function writeFooters(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    const bottomMargin = doc.page.margins.bottom;
    // Writing inside the bottom margin would otherwise trigger a page break.
    doc.page.margins.bottom = 0;
    const y = doc.page.height - 32;
    doc
      .font('Helvetica')
      .fontSize(7.5)
      .fillColor('#555555')
      .text(PDF_FOOTER_TEXT, MARGIN, y, { width: doc.page.width - MARGIN * 2, align: 'center', lineBreak: false });
    doc.text(`Page ${index - range.start + 1} of ${range.count}`, MARGIN, y + 10, {
      width: doc.page.width - MARGIN * 2,
      align: 'center',
      lineBreak: false,
    });
    doc.page.margins.bottom = bottomMargin;
  }
}

/** Lays the report out on `doc` and ends it. */
export function renderPdfReport(doc: PDFKit.PDFDocument, data: HealthExportData): void {
  const report = new Report(doc);
  const selected = new Set(data.datasets);
  const readings = byMetric(data.readings);
  const units = new Units(data.labUnits);

  writeHeader(report, data);

  if (selected.has('labs')) writeLabs(report, readings, units);

  const trendKeys = [
    ...(selected.has('body') ? BODY_KEYS : []),
    ...(selected.has('vitals') ? VITAL_KEYS : []),
    ...(selected.has('labs') ? LAB_TREND_KEYS : []),
  ];
  if (trendKeys.length > 0) writeTrends(report, readings, trendKeys, units);

  const summaryKeys = [...(selected.has('body') ? BODY_KEYS : []), ...(selected.has('vitals') ? VITAL_KEYS : [])];
  if (summaryKeys.length > 0) writeSummary(report, readings, summaryKeys, data.range.to, units);

  if (selected.has('wellness')) writeWellness(report, readings, data.range.to);
  if (selected.has('documents')) writeDocuments(report, data);
  if (selected.has('progress_photos')) writeProgressPhotos(report, data);

  writeFooters(doc);
  doc.end();
}

/**
 * The PDF as a byte stream. `compress: false` keeps the content streams
 * readable, which the text-based tests rely on.
 */
export function pdfExportStream(data: HealthExportData, options: { compress?: boolean } = {}): Readable {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: MARGIN, left: MARGIN, right: MARGIN, bottom: MARGIN + FOOTER_RESERVE },
    bufferPages: true,
    compress: options.compress ?? true,
    info: { Title: `${APP_NAME} health report`, Creator: APP_NAME },
  });

  try {
    renderPdfReport(doc, data);
  } catch (error) {
    doc.destroy(error instanceof Error ? error : new Error(String(error)));
  }

  return doc;
}
