import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ACCENT_COLOR, THEME_COLOR } from '@app/shared';
import * as paths from '../../components/common/brandMarkPaths.generated';

// =============================================================================
// Generated brand assets
// =============================================================================
//
// `apps/web/scripts/generate-icons.py` writes the two SVG masters and
// `brandMarkPaths.generated.ts`. Nothing rasterises or re-validates them, so a
// hand edit (or a half-run rebrand) would drift silently. These guards pin the
// shape the generator promises, against the shared constants and not against
// today's colour values, so a rebrand keeps them green. Manifest icon file
// existence is already covered by `pwa/manifest.test.ts`.
// =============================================================================

const webRoot = resolve(__dirname, '..', '..', '..');
const count = (haystack: string, needle: string) => haystack.split(needle).length - 1;

describe.each(['public/icons/source.svg', 'public/favicon.svg'])('%s', (relPath) => {
  const svg = readFileSync(resolve(webRoot, relPath), 'utf8');

  it('starts with the generated-file header', () => {
    expect(svg).toMatch(/^<\?xml[^>]*\?>\s*<!--\s*GENERATED by apps\/web\/scripts\/generate-icons\.py/);
  });

  it('has exactly one THEME_COLOR fill (the plate)', () => {
    expect(count(svg, `fill="${THEME_COLOR}"`)).toBe(1);
  });

  it('has exactly one ACCENT_COLOR fill (the sun)', () => {
    expect(count(svg, `fill="${ACCENT_COLOR}"`)).toBe(1);
  });

  it('paints the road white', () => {
    expect(count(svg, 'fill="#ffffff"')).toBe(1);
    expect(svg).toMatch(/<path [^>]*fill="#ffffff"/);
  });

  it('draws the sun as a circle in the accent colour', () => {
    expect(svg).toMatch(new RegExp(`<circle [^>]*fill="${ACCENT_COLOR}"`));
  });
});

describe('brandMarkPaths.generated.ts', () => {
  it('starts with the generated-file header', () => {
    const src = readFileSync(
      resolve(webRoot, 'src/components/common/brandMarkPaths.generated.ts'),
      'utf8',
    );

    expect(src).toMatch(/^\/\/ GENERATED by apps\/web\/scripts\/generate-icons\.py/);
  });

  it('exports a positive viewBox and plate radius', () => {
    expect(paths.BRAND_MARK_VIEWBOX).toBeGreaterThan(0);
    expect(paths.BRAND_MARK_PLATE_RADIUS).toBeGreaterThan(0);
  });

  it.each([
    'BRAND_MARK_PLATE_STANDARD',
    'BRAND_MARK_PLATE_COMPACT',
    'BRAND_MARK_GLYPH_STANDARD',
    'BRAND_MARK_GLYPH_COMPACT',
  ] as const)('%s has a non-empty closed road path and a sun circle', (name) => {
    const geometry = paths[name];

    expect(typeof geometry.road).toBe('string');
    expect(geometry.road.length).toBeGreaterThan(0);
    expect(geometry.road.startsWith('M')).toBe(true);
    expect(geometry.road.endsWith('Z')).toBe(true);
    expect(geometry.sun.r).toBeGreaterThan(0);
    expect(geometry.sun.cx).toBeGreaterThan(0);
    expect(geometry.sun.cy).toBeGreaterThan(0);
  });

  it('keeps the plate road in sync with the favicon (compact geometry)', () => {
    const favicon = readFileSync(resolve(webRoot, 'public/favicon.svg'), 'utf8');

    expect(favicon).toContain(`d="${paths.BRAND_MARK_PLATE_COMPACT.road}"`);
  });
});
